name: "PR reviewer remind slack notification action"
description: "Automatically send Slack notification for left PRs to reviewers"
author: "KanghyunJeon"

branding:
  icon: 'bell'
  color: 'green'

inputs:
  github-developer-id-mapping:
    description: "String that we need for mapping from Github ID to Slack ID. Ex) KanghyunJeon:UUABCDEFG,member:UuHIJKLMN "
    required: true
  slack-channel-id:
    description: "Slack channel ID"
    required: true
  slack-message-lang:
    description: "Optional for preferred language"
    required: false
    default: 'en'

  slack-webhook-url:
    description: "Choice 1 : Slack webhook url."
    required: true
  slack-webhook-username:
    description: "Optional for Choice 1 : change Slack webhook's username."
    required: false

  slack-bot-token:
    description: "Choice 2 : Slack bot token."
    required: true

  exclude-draft-prs:
    description: "Optional for exclude Draft PRs"
    required: false

runs:
  using: node20
  main: dist/index.js